package application;

import java.net.URL;
import java.util.LinkedList;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableColumn;

public class CargarInventarioController implements Initializable {
	@FXML
	private Button ButtonCargar;
	@FXML
	private TableView<InventarioAlba> Tablainfo;
	@FXML
	private TableColumn<InventarioAlba, String> CantidadtotalColumn;
	
	ObservableList<InventarioAlba> datos=FXCollections.observableArrayList();
	DatosCantidad data;

	// Event Listener on Button[#ButtonCargar].onMouseClicked
	@FXML
	public void CargarBoton(MouseEvent event) {
		// TODO Autogenerated
		LinkedList<InventarioAlba> data1 = data.getDatos();
		for (InventarioAlba a : data1) {
			this.datos.add(a);
		}
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		this.data = new DatosCantidad();
		this.CantidadtotalColumn.setCellValueFactory(new PropertyValueFactory<>("cantidadTotal"));
		Tablainfo.setItems(this.datos);
		
	}
}
